# Generated by Django 2.2.7 on 2019-12-16 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filer', '0011_auto_20190418_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlickGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Gallery name')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('width_units', models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='width units')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('height_units', models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='height units')),
                ('autoplay', models.BooleanField(default=True, help_text='Autoplays after the page loads', verbose_name='Autoplay')),
                ('autoplay_speed', models.IntegerField(default=3000, help_text='(in miliseconds)', verbose_name='Autoplay speed')),
                ('arrows', models.BooleanField(default=True, help_text='Enable previous/next arrows', verbose_name='Arrows')),
                ('dots', models.BooleanField(default=True, help_text='Enable dot indicators', verbose_name='Dots')),
                ('draggable', models.BooleanField(default=True, help_text='Enable mouse dragging', verbose_name='Draggable')),
                ('fade', models.BooleanField(default=False, help_text='Enable fading', verbose_name='Fade')),
                ('infinite', models.BooleanField(default=False, help_text='Enable infinite loop sliding', verbose_name='Infinite')),
                ('initial_slide', models.PositiveIntegerField(default=0, help_text='Number of the slide to start on (counting from 0)', verbose_name='Initial slide')),
                ('pause_on_hover', models.BooleanField(default=True, help_text='Pause when the gallery is hovered over or focused on', verbose_name='Pause on hover/focus')),
                ('folders', models.ManyToManyField(blank=True, to='filer.Folder')),
                ('thumbnail_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.ThumbnailOption', verbose_name='Thumbnail configuration')),
            ],
            options={
                'verbose_name': 'Slick gallery',
                'verbose_name_plural': 'Slick gallery',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Slide text content')),
                ('alternative_url', models.URLField(blank=True, default=None, null=True, verbose_name='Alternative image url')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsplugin_slick_gallery.SlickGallery', verbose_name='Slick gallery')),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
            },
        ),
        migrations.CreateModel(
            name='SlickGalleryPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_gallery_slickgalleryplugin', serialize=False, to='cms.CMSPlugin')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsplugin_slick_gallery.SlickGallery', verbose_name='Choose a gallery')),
            ],
            options={
                'verbose_name': 'Slick gallery add-on',
                'verbose_name_plural': 'Slick gallery add-ons',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
