# Generated by Django 2.2.7 on 2019-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_slick_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='text_transform_left',
            field=models.IntegerField(default=15, help_text='(in percents)', verbose_name='Move text from the left'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='text_transform_top',
            field=models.IntegerField(default=0, help_text='(in percents)', verbose_name='Move text from the top'),
        ),
    ]
